# Where should we write the GIF?
Output output/coretilus.gif

# Set up a 1200x600 terminal with 15px font.
Set FontSize 20
Set Width 1200
Set Height 800
Set TypingSpeed 100ms

# Type a command in the terminal.
Sleep 700ms
Type "sl /"
Sleep 1500ms

# Run the command by pressing enter.
Enter

# Admire the output for a bit.
Sleep 9s

# Type a command in the terminal.
Type "gti push origin main"
Sleep 1500ms

# Run the command by pressing enter.
Enter

# Admire the output for a bit.
Sleep 8s
